### ISSUE TITLE
datadog monitors.

### ISSUE THREAD

**Issue by oleksandr-shkovyra** [Signiant/datadog-deepsecurity-event-forwarder#1]
@haggaret @dnorth98 How can i create datadog monitor, based on that event?
Also is it possible to put more information into this event?
From my perspective it is not so usefull.

Also when you sent test data, you will receive an error:

`'Rank': KeyError
Traceback (most recent call last):
File "/var/task/lambda-function.py", line 79, in lambda_handler
current_rank = ds_event_dict['Rank']
KeyError: 'Rank'`

KeyError:
`0: KeyError
Traceback (most recent call last):
File "/var/task/lambda-function.py", line 62, in lambda_handler
ds_event_dict = json.loads(event['Records'][0]['Sns']['Message'])[0]
KeyError: 0
`

KeyError:
`'Rank': KeyError
Traceback (most recent call last):
File "/var/task/lambda-function.py", line 79, in lambda_handler
current_rank = ds_event_dict['Rank']
KeyError: 'Rank'`

**Comment by oleksandr-shkovyra** [comment]
Of course, i understand that problem in data which we recieved, from trendmicro.
But in that case we should handle such errors.

**Comment by dnorth98** [comment]
Hmmm...interesting there is no Rank field.  That's kinda important to how the solution decides whether to send an event to Datadog.  Do you have a sample event that is coming in with no Rank you could share?

Totally agree that we should handle this though.  I'm thinking if an event comes in with no rank, we could always forward it to Datadog.  Or we never forward them.  Any thoughts which way you think it should go @cfifua ?

**Comment by oleksandr-shkovyra** [comment]
@dnorth98 let's sent an items without rank. Unfortunately, i can't share event without Rank.

**Comment by dnorth98** [comment]
I checked in a fix with commit https://github.com/Signiant/datadog-deepsecurity-event-forwarder/commit/ffeed0d94196ea1086387aaa7bbace7c1b2787d5 to handle when a Rank is not provided (we just default it to zero)
